version: '3'

services:
  sla_report_automation_dev:
    container_name: sla_report_automation_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .sla_report_automation_dev.env

  sla_report_automation_bash:
    container_name: sla_report_automation_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .sla_report_automation_dev.env

  sla_report_automation_test:
    container_name: sla_report_automation_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .sla_report_automation_dev.env
